# Generated by Django 5.1 on 2024-09-05 03:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Imagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_ul", models.CharField(max_length=1000)),
                ("file_size_mb", models.IntegerField()),
                ("filename", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Oficina",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "logo",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("empresa_nome", models.CharField(max_length=255)),
                ("cnpj", models.CharField(max_length=255)),
                (
                    "home_link",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "maps_link",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parcela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identificacao", models.CharField(max_length=255)),
                ("parcela", models.CharField(max_length=50)),
                ("vencimento", models.CharField(max_length=50)),
                ("situacao", models.CharField(max_length=50)),
                ("valor", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                (
                    "senha",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_nota", models.CharField(max_length=255)),
                ("data_emissao", models.CharField(max_length=10)),
                ("valor_nota", models.CharField(max_length=255)),
                ("destinatario", models.CharField(max_length=255)),
                ("cnpj", models.CharField(max_length=255)),
                ("nome_carro", models.CharField(max_length=255)),
                (
                    "Imagens",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nota",
                        to="core.imagem",
                    ),
                ),
                (
                    "links",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nota",
                        to="core.link",
                    ),
                ),
                (
                    "oficina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notas",
                        to="core.oficina",
                    ),
                ),
                (
                    "parcelas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nota",
                        to="core.parcela",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="oficina",
            name="dono",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oficina",
                to="core.usuario",
            ),
        ),
    ]
