# Generated by Django 5.1 on 2024-09-06 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_oficina_dono_delete_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nota",
            name="Imagens",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nota",
                to="core.imagem",
            ),
        ),
        migrations.AlterField(
            model_name="nota",
            name="links",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nota",
                to="core.link",
            ),
        ),
    ]
