# Generated by Django 5.1 on 2024-09-06 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_nota_imagens_alter_nota_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nota",
            name="parcelas",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nota",
                to="core.parcela",
            ),
        ),
    ]
