# Generated by Django 5.1 on 2024-09-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_nota_cliente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nota",
            name="Imagens",
        ),
        migrations.RemoveField(
            model_name="nota",
            name="links",
        ),
        migrations.RemoveField(
            model_name="nota",
            name="parcelas",
        ),
        migrations.AddField(
            model_name="nota",
            name="Imagens",
            field=models.ManyToManyField(
                blank=True, related_name="nota", to="core.imagem"
            ),
        ),
        migrations.AddField(
            model_name="nota",
            name="links",
            field=models.ManyToManyField(
                blank=True, related_name="nota", to="core.link"
            ),
        ),
        migrations.AddField(
            model_name="nota",
            name="parcelas",
            field=models.ManyToManyField(
                blank=True, related_name="nota", to="core.parcela"
            ),
        ),
    ]
