# Generated by Django 5.1 on 2024-09-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_nota_imagens_remove_nota_links_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="link",
            old_name="file_ul",
            new_name="file_url",
        ),
    ]
