# Generated by Django 5.1 on 2024-09-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_rename_file_ul_link_file_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="link",
            old_name="file_size_mb",
            new_name="size",
        ),
        migrations.RenameField(
            model_name="link",
            old_name="name",
            new_name="title",
        ),
    ]
