# Generated by Django 5.1 on 2024-09-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_rename_file_size_mb_link_size_rename_name_link_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcela",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("Atrasado", "Atrasado"),
                    ("Pendente", "Pendente"),
                    ("Pago", "Pago"),
                ],
                max_length=50,
            ),
        ),
    ]
