# Generated by Django 5.1 on 2024-09-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_nota_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcela",
            name="file_url",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
