# Generated by Django 5.1 on 2024-09-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_parcela_file_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcela",
            name="numeracao_boleto",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
