# Generated by Django 5.1 on 2024-09-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_parcela_numeracao_boleto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="file_url",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
